export type ExportAdapterErrorCode =
  | "INVALID_DOCUMENT_DIMENSIONS"
  | "PSD_DIMENSION_LIMIT_EXCEEDED"
  | "TIFF_PIXEL_BUDGET_EXCEEDED"
  | "RASTER_MEMORY_BUDGET_EXCEEDED"
  | "RASTER_LAYER_REQUIRED"
  | "RASTER_ASSET_MISMATCH"
  | "RASTER_DECODE_FAILED"
  | "CHARACTER_RIG_TEMPLATE_INVALID"
  | "CHARACTER_SOURCE_REQUIRED"
  | "CHARACTER_SOURCE_INTEGRITY_FAILED"
  | "CHARACTER_SOURCE_DECODE_FAILED"
  | "CHARACTER_SOURCE_CANVAS_MISMATCH"
  | "CHARACTER_SOURCE_COMPOSITE_MISMATCH";

export class ExportAdapterError extends Error {
  constructor(
    readonly code: ExportAdapterErrorCode,
    message: string,
  ) {
    super(message);
  }
}
